config/routes.rb
Fleetopedia::Application.routes.draw do

  

  
  root :to => 'home#index'
  resources :vehicles
  resources :drivers
  resources :people

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :vehicle_drivers
  has_many :vehicles, through: :vehicle_drivers
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :person_addresses, :class_name => "PersonAddress", :dependent => :destroy
  has_many :person_vehicles
  has_many :time_slots

  accepts_nested_attributes_for :person_addresses
end

app/models/person_address.rb
class PersonAddress < ActiveRecord::Base
  belongs_to :person
end

app/models/person_vehicle.rb
class PersonVehicle < ActiveRecord::Base
  has_many :people
  has_many :vehicle_drivers
  has_many :vehicles, :through => "VehicleDrivers"
  has_many :drivers, :through => "VehicleDrivers"
  has_many :time_slots
end

app/models/travel_slot.rb
class TravelSlot < ActiveRecord::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :vehicle_drivers
  has_many :drivers, through: :vehicle_drivers
end

app/models/vehicle_driver.rb
class VehicleDriver < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :driver
  belongs_to :travel_slot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  
  def index
    @drivers = Driver.find(:all)
  end

  def new
    @driver = Driver.new
  end

  def show
    @driver = Driver.find(params[:id])
    
  end

  def create
    @driver = Driver.new(driver_params)
    if @driver.save
      redirect_to drivers_path
    else
      render 'new'
    end
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  def update
    @driver = Driver.find(params[:id])
    if @driver.update_attributes(driver_params)
      redirect_to drivers_path
    else
      render 'edit'
    end
  end

  def destroy
    Driver.find(params[:id]).destroy
    redirect_to drivers_path
  end

  private

  def driver_params
    params.require(:driver).permit(:license_no, :name, :dob, :address, :contact_no, :nationality)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    @vehicle_driver_assignments = VehicleDriver.joins(:vehicle).joins(:driver)
      .where("vehicle_drivers.created_at >= ? and vehicle_drivers.created_at < ? and status =?", 
        DateTime.now.beginning_of_day.utc, DateTime.now.end_of_day.utc, "assigned").group_by {|vd| vd.vehicle_id }
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.find(:all)
  end

  def new
    @person = Person.new
    @person.person_addresses.build
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      #redirect_to people_path 
      render :partial => 'person', :object => @person
    else
      render 'new'
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(person_params)
      redirect_to person_path(@person)
    else
      render 'edit'
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end
  
  private
  def person_params
    params.require(:person).permit(:mnemonic, :name, :email, :oranization, 
                                   person_addresses_attributes: [:id, :address, :city, :state, :country, :pincode, :_destory])
  end
end

app/controllers/person_addresses_controller.rb
class PersonAddressesController < ApplicationController
  def create
  end

  private
  def person_addresses_params
    params[:person_address].permit[:person_id, :address, :city, :state, :country]
  end
end

app/controllers/person_vehicles_controller.rb
class PersonVehiclesController < ApplicationController
  def create
  end

  private
  def person_vehicles_params
    params[:person_vehicle].permit[:person_id, :vehicle_drivers_id, :travel_slot_id]
  end
end

app/controllers/vehicle_drivers_controller.rb
class VehicleDriversController < ApplicationController
  def create
      
  end

  private
  def vehicles_drivers_params
    params[:vehicle_driver].permit[:vehicle_id, :driver_id, :travel_slot_id]
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	
	def index
		@vehicles = Vehicle.find(:all)
	end

	def new
		@vehicle = Vehicle.new
	end

	def show
	 	@vehicle = Vehicle.find(params[:id])
	 	@current_driver = @vehicle.drivers.where("vehicle_drivers.created_at>=?", DateTime.now.beginning_of_day.utc).order("vehicle_drivers.created_at").last
	 	# if params[:unassign_driver]
	 	# 	VehicleDriver.where("vehicle_id=? and driver_id=?", @vehicle.id, @current_driver.id).order("created_at").update(:status => "Unassigned")
	 	# 	@current_driver = @vehicle.drivers.order("vehicle_drivers.created_at").last
	 	# end
	end

	def create
		@vehicle = Vehicle.new(vehicle_params)
  	if @vehicle.save
      redirect_to vehicles_path, notice: 'Test was successfully created.'
  	else
      render 'new'
  	end
	end

	def edit
		@vehicle = Vehicle.find(params[:id])
		@drivers = Driver.joins("left join vehicle_drivers on vehicle_drivers.driver_id = drivers.id and vehicle_drivers.created_at > '#{DateTime.now.beginning_of_day.utc}'")
							.where("vehicle_drivers.driver_id is null or vehicle_drivers.vehicle_id =?", @vehicle.id)
		@current_driver = @vehicle.drivers.where("vehicle_drivers.created_at>=? and vehicle_drivers.status = ?", DateTime.now.beginning_of_day.utc,"assigned").order("vehicle_drivers.created_at").last
	end

	def update
		@vehicle =Vehicle.find(params[:id])
		if params[:unassign_driver]
	 		VehicleDriver.where("vehicle_id=?", @vehicle.id).update_all(:status => "unassigned")
	 		redirect_to root_path
	 	elsif params[:driver_id].present?
			@vehicle.vehicle_drivers.new(driver: Driver.find(params[:driver_id]), :status => "assigned")
			if @vehicle.update_attributes(vehicle_params)
				redirect_to vehicle_path(@vehicle)
			else
				render 'edit'
			end
		end

		
	end

	def destroy
		Vehicle.find(params[:id]).destroy
		redirect_to vehicles_path
	end

	private

	def vehicle_params
		params.require(:vehicle).permit(:reg_no, :country, :seating, :owner)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_addresses_helper.rb
module PersonAddressesHelper
end

app/helpers/person_vehicles_helper.rb
module PersonVehiclesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/helpers/vehicles_drivers_helper.rb
module VehiclesDriversHelper
end

app/views/drivers/_driver.html.erb
<h1>Driver</h1>
<%= form_for @driver do |f| %>
  <p><label for="driver_license_no">License Number</label>:
    <%= f.text_field :license_no %></p>
  <p><lable for="driver_name">Name</label>:
    <%= f.text_field :name %></p>
  <p><label for="driver_dob">Date of Birth</label>:
    <%= f.text_field :dob %></p>
  <p><label for="driver_address">Address</label>:
    <%= f.text_field :address %></p>
  <p><label for="driver_contact_no">Contact Number</label>:
    <%= f.text_field :contact_no %></p>
  <p><label for="driver_nationality">Nationality</label>:
    <%= f.text_field :nationality %></p>
  <%= f.submit %>
<% end %>
  <p><%= link_to "Drivers Listing", drivers_path %></p>

app/views/drivers/edit.html.erb
<%= render partial: 'driver' %>

app/views/drivers/index.html.erb
<% if @drivers.blank? %>
  <p> No drivers added yet <p>
<% else %>
  <p> Drivers List <p>
    <ul>
      <% @drivers.each do |driver| %>
        <li>
          <%= link_to driver.license_no, driver_path(driver) %>
          <%= link_to "Edit", edit_driver_path(driver) %>
          <%= link_to "Delete", driver_path(driver), method: :delete %>
        </li>
      <% end %>
<% end %>
<p><%= link_to "Add Driver", new_driver_path %></p>

app/views/drivers/new.html.erb
<%= render partial: 'driver' %> 

app/views/drivers/show.html.erb
<p> Listed below is the driver detail </p>
  <ul>
    <li><%= @driver.license_no %></li>
    <li><%= @driver.name %></li>
    <li><%= @driver.dob %></li>
    <li><%= @driver.address %></li>
    <li><%= @driver.contact_no %></li>
    <li><%= @driver.nationality %></li>
  </ul>
<p><%= link_to "Add Driver", new_driver_path %></p>
<p><%= link_to "Driver Listing", drivers_path %></p>

app/views/people/_address_fields.html.erb
<p>
  <%= f.label :address, "Address" %><br />
  <%= f.text_area :address, :rows => 3 %>
</p>
<p>
  <%= f.label :city, "City" %><br />
  <%= f.text_field :city %>
 </p>
 <p> 
  <%= f.label :state, "State" %><br />
  <%= f.text_field :state %>
</p>
<p>
  <%= f.label :country, "Country" %><br />
  <%= f.text_field :country %>
</p>
<p>
  <%= f.label :pincode, "PinCode" %><br />
  <%= f.text_field :pincode %>
</p>

app/views/people/_person.html.erb
<h1> Person Details </h1>
<%= form_for @person do |f| %>
  <p><label for="mnemonic">Person ID</label>:
    <%= f.text_field :mnemonic %></p>
  <p><label for="person_name">Name</label>:
    <%= f.text_field :name %></p>
  <p><label for="person_email">Email ID</label>:
    <%= f.text_field :email %></p>

    <%= f.fields_for :person_addresses  do |address| %>
      <%= render 'address_fields', :f => address %>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<%= render partial: 'person' %>

app/views/people/index.html.erb
<h1>Associate List</h1>
<% if @people.blank? %>
  <p> No associates </p>
<% else %>
  <ol>
    <% @people.each do |person| %>
    <li>
      <%= link_to person.mnemonic, person_path(person) %>
      <%= link_to "Edit", edit_person_path(person) %>
      <%= link_to "Delete", person_path(person), method: :delete %>
    </li>
    <% end %>
  </ol>
<% end %> 
<%= link_to "Add Associate", new_person_path %>  

app/views/people/new.html.erb
<%= render partial: 'person' %>

app/views/people/show.html.erb
<h1>Associate Details</h1>
<% if @person.blank? %>
  <p> Not found </p>
<% else %>
  <p>Name: <%= @person.name %></p>
  <p>Person ID: <%= @person.mnemonic %></p>
  <p>Email: <%= @person.email %></p>
  <% for person_addres in  @person.person_addresses %>
    <li> Address:<%= person_addres.address %> </li>
    <li> City:<%= person_addres.city %></li>
    <li> State:<%= person_addres.state %></li>
    <li> Country:<%= person_addres.country %></li>
    <li> PinCode:<%= person_addres.pincode %></li>
  <% end %>
<% end %>

<%= link_to "List Associates", people_path %>
<%= link_to "Edit", edit_person_path %>
<%= link_to "New", new_person_path %>

 

app/views/vehicles/_vehicle.html.erb
<h1> Vehicle </h1>
<%= form_for @vehicle do |f| %>
  <p><label for="vehicle_reg_no">Registration Number</label>:
    <%= f.text_field :reg_no %></p>
  <p><label for="vehicle_county">Country</label>:
    <%= f.text_field :country %></p>
  <p><label for="vehicle_seating">Seating</label>:
    <%= f.text_field :seating %></p>
  <p><label for="vehicle_owner">Owner</label>
    <%= f.text_field :owner %></p>
    <% if @current_driver %>
    <%= select_tag "driver_id", options_from_collection_for_select(@drivers, "id", "name", @current_driver.id) %>
    <%= f.submit 'Unassign Driver', :name => 'unassign_driver' %>
   <% else %>   
     <%= select_tag "driver_id", options_from_collection_for_select(@drivers, "id", "name"), prompt: "Select Driver" %>
   <% end %>
  <%= f.submit %>
<% end %>
<p><%= link_to "Vehicles listing", vehicles_path%></p>

app/views/vehicles/edit.html.erb
<%= render partial: 'vehicle' %>

app/views/vehicles/index.html.erb
<% if @vehicles.blank? %>
	<p> There are no vehicles </p>
<% else %>
  <p> Vehicles list </p>
	<ul>
		<% @vehicles.each do |vehicle| %>
			<li>
        <%= link_to vehicle.reg_no, vehicle_path(vehicle) %> 
        <%= link_to "Edit", edit_vehicle_path(vehicle) %>
        <%= link_to "Delete", vehicle_path(vehicle), method: :delete %>
      </li>
		<% end %>
	</ul>
<% end %>
<p><%= link_to "Add Vehicle", new_vehicle_path %></p>

app/views/vehicles/new.html.erb
<%= render partial: 'vehicle' %>

app/views/vehicles/show.html.erb
<p> Listed below is the vehicle ></p>
	<ul>
			<li><%= @vehicle.reg_no %></li>
			<li><%= @vehicle.country %></li>
			<li><%= @vehicle.seating %></li>
			<li><%= @vehicle.owner %></li>
      <% if @current_driver %>
        <li>Current Driver: <%= @current_driver.name %></li>
      <% end %>
	</ul>
<p><%= link_to "Add new Vehicle", new_vehicle_path %></p>
<p><%= link_to "Vehicle Listing", vehicles_path %></p>